#!/bin/bash
set -eu
/usr/bin/docker pull registry:2
/usr/bin/docker create --env-file /etc/registry/registryrc --volume /var/lib/registry:/registry --publish 5000:5000 --name registry registry:2
exec /usr/bin/docker start --attach=true registry
