#!/bin/bash
# Este archivo fue creado con "oasproj init" y será sobre-escrito con "oasproj update --force"

set -eu

# cosas para hacer antes de instalar el paquete aquí:

echo OAS before install

echo Verificando existencia de certificados para Docker Swarm

if [ ! -e "/etc/ci-swarm-manage/certs.d/ca.pem" -o ! -e "/etc/ci-swarm-manage/certs.d/cert.pem" -o ! -e "/etc/ci-swarm-manage/certs.d/key.pem" ]
then
  fqdn="$(hostname -f)"
  echo
  echo
  echo
  echo "No se encuentran los certificados de ci-swarm-manage en /etc/ci-swarm-manage/certs.d/, se deben generar en oas-ci-swarm-ca con el comando '/usr/sbin/swarm-ci-create-server-cert swarm ${fqdn}' luego traer los archivos desde oas-ci-swarm-ca en '/var/lib/docker-ci-swarm-ca/swarm/*' hasta este servidor en la ruta '/etc/ci-swarm-manage/certs.d/'"
  echo
  echo
  echo
  exit 1
fi
